VTuberSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("webpush/", include("webpush.urls")),
    path("", include("web.urls", namespace="web"))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [path("signup/", views.SignUp.as_view(), name="signup")]

api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("get_stream", views.get_stream_list, name="get_stream"),
    path("notify-modal", views.get_notify_modal, name="get_notify_modal"),
    path("register_subscription", views.register_sub_channel, name="register_subscription"),
    path("set_is_freechat", views.set_is_freechat, name="set_is_freechat"),
    path("remove_stream", views.remove_stream, name="remove_stream"),
    path("refresh", views.refresh, name="refresh"),
    path("notify", views.notify, name="notify"),
    path("youtube_callback", views.youtube_callback, name="youtube_callback")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from web.models import Channel


class CustomUser(AbstractUser):
    channel_id = models.CharField(max_length=24, unique=True)
    channel = models.ManyToManyField(Channel, related_name="user")
    nickname = models.CharField(max_length=12)
    timezone = models.TextField(max_length=32, default="Asia/Tokyo")

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.forms import CharField
from django.core.exceptions import ValidationError
from .models import CustomUser
from scrape.getChannel import get_subbed_channel

import requests


class CustomForm(UserCreationForm):
    channel_id = CharField(required=True,
                           label="チャンネルID",
                           error_messages={"invalid": "不正なIDです。",
                                           "exist": "既に存在します。"})
    nickname = CharField(required=True, max_length=12, label="ニックネーム")
    email = CharField(required=False, max_length=254, label="メールアドレス")

    class Meta:
        model = CustomUser
        fields = ("username", "channel_id", "nickname", "email", "password1", "password2")

    def save(self, commit=True):
        cleaned_data = super(CustomForm, self).clean()
        if self.errors:
            return self.errors
        user = super(CustomForm, self).save(commit=False)
        user.channel_id = cleaned_data["channel_id"]
        user.nickname = cleaned_data["nickname"]
        if commit:
            user.save()
        return user

    def clean_channel_id(self):
        if CustomUser.objects.filter(channel_id=self.cleaned_data["channel_id"]):
            raise ValidationError(self.fields["channel_id"].error_messages["exist"])
        if len(self.cleaned_data["channel_id"]) > 24:
            raise ValidationError(self.fields["channel_id"].error_messages["invalid"])
        res = requests.get(f"https://www.youtube.com/channel/{self.fields['channel_id']}")
        if not res.status_code == 200:
            raise ValidationError(self.fields["channel_id"].error_messages["invalid"])
        return self.cleaned_data["channel_id"]

    def clean_nickname(self):
        if not self.cleaned_data["nickname"]:
            raise ValidationError("Please Enter your nickname.")
        if len(self.cleaned_data["nickname"]) > 12:
            raise ValidationError("Nickname must be <= 12 char.")
        return self.cleaned_data["nickname"]


class SignUp(generic.CreateView):
    form_class = CustomForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

templates/accounts/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="header"><h3 class="text-center">新規登録</h3></div>
        <section class="common-form w-50 mx-auto">
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <span class="text-danger">{{ form.errors }}</span>
                {% endif %}
                <div class="form-group">
                    <label for="{{ form.username.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.username.label }}</label>
                    {{ form.username|add_class:"form-control form-control-sm" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.channel_id.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.channel_id.label }}</label>
                    {{ form.channel_id|add_class:"form-control form-control-sm" }}
                    <span class="small">Youtubeトップページ→右上のユーザーアイコン→チャンネルのURLから確認できます。</span>
                    <a class="toggle-img small" data-toggle="modal" data-target="#img-modal" href="#">詳細</a>
                </div>
                <div class="form-group">
                    <label for="{{ form.nickname.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.nickname.label }}</label>
                    {{ form.nickname|add_class:"form-control form-control-sm" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.email.label }}</label>
                    {{ form.email|add_class:"form-control form-control-sm" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password1.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.password1.label }}</label>
                    {{ form.password1|add_class:"form-control form-control-sm" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.password2.id_for_label }}"
                           class="col-form-label col-form-label-sm py-0">{{ form.password2.label }}</label>
                    {{ form.password2|add_class:"form-control form-control-sm" }}
                </div>
                <button type="submit" class="btn btn-info mt-2">Sign up</button>
            </form>
        </section>
    </div>
    <div class="modal fade" id="img-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" style="max-width: 1000px">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <img src="{% static 'images/ChannelIdDesc.jpg' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/update.html
{% extends "base.html" %}
{% block content %}
    <div class="align-content-center">
        <div class="w-75 mx-auto mt-4">
            <form role="form" method="post">
                {% csrf_token %}
                <div class="form-group row text-dark">
                    <label for="id_username" class="col-form-label col-md-2">Username: </label>
                    <div class="col-md-10">
                        <input id="id_username" class="form-control" type="text" placeholder="Username" readonly
                               value="{{ user.username }}">
                    </div>
                </div>
                <div class="form-group row text-dark">
                    <label for="id_nickname" class="col-form-label col-md-2">Nickname: </label>
                    <div class="col-md-10">
                        {{ form.nickname }}
                    </div>
                </div>
                <div class="form-group row text-dark">
                    <label for="id_channel_id" class="col-form-label col-md-2">Channel ID: </label>
                    <div class="col-md-10">
                        {{ form.channel_id }}
                    </div>
                    {% if error %}
                        <div class="invalid-feedback">{{ code }}: {{ message }}</div>
                    {% endif %}
                </div>
                <div class="form-group row text-dark">
                    <label for="is_email" class="col-form-label col-md-2">E-mail address: </label>
                    <div class="col-md-10">
                        {{ form.email }}
                    </div>
                </div>
                <button class="btn btn-primary float-lg-right m-auto" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}