VTuberSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("webpush/", include("webpush.urls")),
    path("", include("web.urls", namespace="web"))
]

api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("get_stream", views.get_stream_list, name="get_stream"),
    path("notify-modal", views.get_notify_modal, name="get_notify_modal"),
    path("register_subscription", views.register_sub_channel, name="register_subscription"),
    path("set_is_freechat", views.set_is_freechat, name="set_is_freechat"),
    path("remove_stream", views.remove_stream, name="remove_stream"),
    path("refresh", views.refresh, name="refresh"),
    path("notify", views.notify, name="notify"),
    path("youtube_callback", views.youtube_callback, name="youtube_callback")
]

notify/models.py
from django.db import models

from accounts.models import CustomUser
from web.models import Stream, Channel


class NoticeScheduleStream(models.Model):
    users = models.ManyToManyField(CustomUser, related_name="notice_schedule_streams")
    notice_min = models.IntegerField(default=5)
    stream = models.ForeignKey(Stream, on_delete=models.CASCADE, related_name="notice_schedule_stream")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.stream.title

    class Meta:
        unique_together = ["stream", "notice_min"]


class NoticeScheduleChannel(models.Model):
    users = models.ManyToManyField(CustomUser, related_name="notice_schedule_channels")
    notice_min = models.IntegerField(default=5)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name="notice_schedule_channel")

    def __str__(self):
        return self.channel.title

    class Meta:
        unique_together = ["channel", "notice_min"]

notify/forms.py
from django import forms
from web.models import *


class NoticeForm(forms.Form):
    target_type = forms.ChoiceField(
        choices=(("channel", "Channel"), ("stream", "Stream"))
    )
    action = forms.ChoiceField(
        choices=(("add", "Add"), ("remove", "Remove"))
    )
    target_id = forms.CharField(
        required=True, max_length=24
    )
    notice_min = forms.IntegerField(required=False, max_value=1440, min_value=1)  # Max: 24h, Min: 1m

    def clean_notice_min(self):
        if not self.cleaned_data.get("notice_min"):
            self.cleaned_data["notice_min"] = 5
        return self.cleaned_data.get("notice_min")

    def clean_target_id(self):
        target = self.cleaned_data.get("target_id")
        target_type = self.cleaned_data.get("target_type")
        if target_type == "channel":
            if not Channel.objects.filter(channel_id=target):
                raise forms.ValidationError("Invalid channel/video ID. or target is not registered.")
        elif target_type == "stream":
            if not Stream.objects.filter(video_id=target):
                raise forms.ValidationError("Invalid channel/video ID. or target is not registered.")
        return target

    def clean_action(self):
        action = self.cleaned_data.get("action")
        if action not in ["add", "remove"]:
            raise forms.ValidationError("Invalid parameter - action")
        return action

    def clean_target_type(self):
        if self.cleaned_data.get("target_type") not in ["channel", "stream"]:
            raise forms.ValidationError("Invalid parameter - target_type")
        return self.cleaned_data.get("target_type")

notify/views.py
from django.utils import timezone
from django.conf import settings
from sendgrid.helpers.mail import From, Mail, To
import sendgrid
from webpush import send_user_notification

from .models import NoticeScheduleStream, NoticeScheduleChannel
from web.models import Stream, Channel
from accounts.models import CustomUser

from logging import getLogger

logger = getLogger(__name__)


def send_mail(user, video_id_list):
    dist = user.email
    if not dist:
        return
    video_list = [Stream.objects.get(video_id=x) for x in video_id_list]
    tz = timezone.pytz.timezone(user.timezone)

    msg = Mail(
        From(settings.MAIL_ADDR),
        To(dist)
    )
    msg.dynamic_template_data = {
        "video_list": [{
            "video_id": x.video_id, "title": x.title, "thumb_url": x.thumb, "channel_id": x.channel_id,
            "channel_name": x.channel.title, "channel_thumb_url": x.channel.thumb}
            for x in video_list],
        "subject": f"{(video_list[0].start_at - timezone.now()).seconds // 60}分後に生放送が開始されます",
        "start_at": video_list[0].start_at.astimezone(tz).strftime("%m{0}%d{1} %H:%M").format(*"月日"),
        "remain_time_min": (video_list[0].start_at - timezone.now()).total_seconds() // 60,
        # "image": "http://youtube.dplab.biz" + static("images/YoutubeLiveSchedulerHeader.jpg"),
        # "unsubscribe": f"http://giftify.dplab.biz{reverse('account:unsubscribe_page')}?email={dist}&c={_condition_id}"
    }
    msg.template_id = "d-fd0b728c820b424dbe63e4154b47cc4b"
    try:
        sg = sendgrid.SendGridAPIClient(settings.SENDGRID_API)
        response = sg.send(msg.get())
    except Exception as e:
        logger.error(e)
        print(e)
        return None
    logger.debug(f"[NOTIFY] Sent a Mail to {user.email}")
    print(f"[NOTIFY] Sent a Mail to {user.email}")
    return dist


def send_web_push(user, video_id):
    stream = Stream.objects.get(video_id=video_id)
    payload = {
        "head": f"ライブが{int((stream.start_at - timezone.now()).total_seconds()//60)}分後に始まります。",
        "body": stream.title,
        "icon": stream.thumb,
        "url": f"https://www.youtube.com/watch?v={stream.video_id}"
    }
    send_user_notification(user=user, payload=payload, ttl=1000)
    print(f"[NOTIFY] Sent a Webpush to {user.username}")


def check_condition():
    def _combine(a, b):
        for k, v in b.items():
            if k in a.keys():
                a[k] += b[k]
            else:
                a[k] = b[k]
            a[k] = list(set(a[k]))
        return a

    user_dict = _combine(check_condition_channel(), check_condition_stream())
    return user_dict


def check_condition_channel():
    cond_list = NoticeScheduleChannel.objects.all()
    now = timezone.now()

    mailing_list = {}
    for cond in cond_list:
        notice_time = now + timezone.timedelta(minutes=cond.notice_min)
        stream_list = cond.channel.stream.filter(start_at__gte=now, start_at__lte=notice_time)
        if stream_list:
            for stream in stream_list:
                try:
                    ns = NoticeScheduleStream.objects.get(stream=stream)
                except NoticeScheduleStream.DoesNotExist:
                    ns = NoticeScheduleStream.objects.create(
                        stream=stream, notice_min=cond.notice_min
                    )
                    ns.users.add(*cond.users.all())

    return mailing_list


def check_condition_stream():
    cond_list = NoticeScheduleStream.objects.filter(is_active=True)
    now = timezone.now()

    mailing_list = {}
    for cond in cond_list:
        notice_time = now + timezone.timedelta(minutes=cond.notice_min)
        if now <= cond.stream.start_at <= notice_time:
            for user in cond.users.all():
                if user.username in mailing_list.keys():
                    mailing_list[user.username] += cond.stream.video_id
                else:
                    mailing_list[user.username] = [cond.stream.video_id]
                cond.is_active = False
                cond.save()
        if now >= cond.stream.start_at:
            cond.is_active = False
            cond.save()

    return mailing_list

templates/notify/notify_modal.html
<div class="modal fade notify-setting-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">通知設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

templates/notify/notify_modal_body.html
{% load widget_tweaks %}
<div class="w-50 mx-auto" style="min-width: 15rem">
    <form method="get" action="{% url "api:notify" %}">
        {#        <div class="form-group">#}
        {#            {% if not stream_cond_list %}#}
        {#                <li>登録されているライブ放送はありません。</li>#}
        {#            {% endif %}#}
        {#            {% for stream_cond in stream_cond_list %}#}
        {#                <div class="custom-control custom-checkbox">#}
        {#                    <input type="checkbox" class="custom-control-input" id="input_{{ stream_cond.stream.video_id }}"#}
        {#                           {% if user in stream_cond.users.all %}checked{% endif %}>#}
        {#                    <label for="input_{{ stream_cond.stream.video_id }}"#}
        {#                           class="custom-control-label">{{ stream_cond.stream.title }}</label>#}
        {#                </div>#}
        {#            {% endfor %}#}
        {#        </div>#}
        {% if type == "stream" %}
            {% include "notify/notify_modal_body_stream.html" %}
        {% elif type == "channel" %}
            {% include "notify/notify_modal_body_channel.html" %}
        {% endif %}
        <div class="form-group">
            <button type="button" class="btn btn-danger mr-auto remove-btn" data-dismiss="modal"
                    onclick="send_notify_settings($('form'), '{% url 'api:notify' %}')">確定
            </button>
        </div>
        <script>
            $("input:checked").parent().addClass("active")
        </script>
    </form>
</div>

templates/notify/notify_modal_body_channel.html
{% load widget_tweaks %}
<input type="hidden" value="{{ channel.channel_id }}" name="target_id">
<div class="form-group">
    <div class="input-group input-group-sm">
        {{ forms.notice_min|add_class:"form-control form-control-sm"|append_attr:"aria-describedby=min_addon"|append_attr:"required" }}
        <div class="input-group-append">
            <small class="input-group-text" id="min_addon">分前に通知</small>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label for="action_add" class="btn btn-sm btn-outline-dark">
            <input id="action_add" type="radio" name="action" value="add" checked>
            有効
        </label>
        <label for="action_remove" class="btn btn-sm btn-outline-dark">
            <input id="action_remove" type="radio" name="action" value="remove">
            無効
        </label>
    </div>
</div>

templates/notify/notify_modal_body_stream.html
{% load widget_tweaks %}
<input type="hidden" value="{{ stream.video_id }}" name="target_id">
<div class="form-group">
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label for="type_stream" class="btn btn-sm btn-outline-dark">
            <input id="type_stream" type="radio" name="target_type" value="stream" checked>
            Stream
        </label>
        <label for="type_channel" class="btn btn-sm btn-outline-dark">
            <input id="type_channel" type="radio" name="target_type" value="channel">
            Channel
        </label>
    </div>
</div>
<div class="pb-4 px-2 video_image">
    <img src="{{ stream.thumb }}" alt="" class="w-100">
</div>
<div class="form-group">
    <div class="input-group input-group-sm">
        {{ forms.notice_min|add_class:"form-control form-control-sm"|append_attr:"aria-describedby=min_addon"|append_attr:"required" }}
        <div class="input-group-append">
            <small class="input-group-text" id="min_addon">分前に通知</small>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <label for="action_add" class="btn btn-sm btn-outline-dark">
            <input id="action_add" type="radio" name="action" value="add" checked>
            有効
        </label>
        <label for="action_remove" class="btn btn-sm btn-outline-dark">
            <input id="action_remove" type="radio" name="action" value="remove">
            無効
        </label>
    </div>
</div>
<script>
    var data = {is_active_stream: {{ data.is_active_stream }}, is_active_channel: {{ data.is_active_channel }}}
    var image = $(".video_image")
    $("input[name='target_type']").on("change", (ev)=>{
        if (ev.target.value === "channel"){
            image.hide()
            $("input[name='target_id']").val("{{ channel.channel_id }}")
        } else if (ev.target.value === "stream"){
            image.show()
            $("input[name='target_id']").val("{{ stream.video_id }}")
        }
    })
</script>

templates/notify/webpush_head_script.html
{% if user.is_authenticated or group %}
  {% load static %}
  <script id="webpush-js" type="text/javascript" src="{% static 'js/webpush.js' %}"></script>
{% endif %}

templates/notify/webpush_head_vapid.html
{% if user.is_authenticated or group %}
  {% load static %}
  <meta name="django-webpush-vapid-key" content="{{ vapid_public_key }}">
{% endif %}

templates/notify/webpush_head_worker.html
{% if user.is_authenticated or group %}
  {% load static %}
  <meta name="service-worker-js" content="{% url 'service_worker' %}">
{% endif %}

templates/notify/webpush_switch.html
{% if user.is_authenticated or group %}
    <div class="nav-item custom-control custom-switch d-flex align-items-center mr-4">
        <input type="checkbox" class="custom-control-input" id="webpush-subscribe-switch"
               {% if group %}data-group="{{ group }}"{% endif %} {% if class %}class="{{ class }}"{% endif %}
               data-url="{{ webpush_save_url }}">
        <label for="webpush-subscribe-switch" class="custom-control-label">Web通知</label>
    </div>
    <div id="webpush-message" hidden></div>
{% endif %}