VTuberSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("webpush/", include("webpush.urls")),
    path("", include("web.urls", namespace="web"))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [path("signup/", views.SignUp.as_view(), name="signup")]

api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("get_stream", views.get_stream_list, name="get_stream"),
    path("notify-modal", views.get_notify_modal, name="get_notify_modal"),
    path("register_subscription", views.register_sub_channel, name="register_subscription"),
    path("set_is_freechat", views.set_is_freechat, name="set_is_freechat"),
    path("remove_stream", views.remove_stream, name="remove_stream"),
    path("refresh", views.refresh, name="refresh"),
    path("notify", views.notify, name="notify"),
    path("youtube_callback", views.youtube_callback, name="youtube_callback")
]

web/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "web"
urlpatterns = [
    path("user", views.user_detail, name="user_detail"),
    path("user/update", login_required(views.UserUpdateView.as_view()), name="user_update"),
    path("channel/<slug:channel_id>", views.channel_detail, name="channel_detail"),
    path("test", views.test, name="test"),
    path("top", views.index, name="top"),
    path("", views.index, name="index"),

]

templates/web/card.html
<div class="card m-1 px-1 pt-1 pb-0 border-{% if type == "live" %}danger{% else %}dark{% endif %} {% if s in notice_list %}border-notice{% endif %}">
    <div>
        <a href="https://www.youtube.com/watch?v={{ s.video_id }}" target="_blank">
            <img class="bd-placeholder-img card-img-top" src="{{ s.thumb }}" alt="">
        </a>
        <div>
            <small class="position-absolute"
                   style="background: rgba(45,45,45,0.75); color: whitesmoke; transform: translateY(-100%); border-top-right-radius: .25rem"
            >{{ s.start_at|date:"Y/n/j G:i" }}</small></div>
    </div>
    <div class="card-body p-1 my-1 ">
        <a href="https://www.youtube.com/watch?v={{ s.video_id }}" target="_blank">
            <small class="card-text text-dark mb-auto">{{ s.title }}</small>
        </a>
    </div>
    <div class="card-footer py-1 px-2 bg-transparent">
        {% if type != "live" %}
            <div class="float-left align-middle text-center h-100" style="width: 2rem" tabindex="0" role="button"
                 data-toggle="popover" data-placement="top"
                 data-content='{% include "web/card_popover.html" with i=i j=j type=type s=s %}'>
                <i class="fas fa-lg fa-ellipsis-v h-100 mx-auto"></i>
            </div>
        {% endif %}
        <a class="btn-sm btn-danger float-right"
           href="https://www.youtube.com/channel/{{ s.channel.channel_id }}" target="_blank"><i
                class="fab fa-youtube"></i></a>
    </div>
</div>

templates/web/card_popover.html
{% if user.is_superuser %}
<div class="custom-control custom-switch">
    <input type="checkbox" {% if s.is_freechat %}checked {% endif %}class="custom-control-input"
           id="id_is_{{ type }}_{{ i }}{% if j %}_{{ j }}{% endif %}"
           onclick="moveToFreechat(this, `#{{ type }}_item_{{ i }}{% if j %}_{{ j }}{% endif %}`, `{% url "api:set_is_freechat" %}`);">
    <label for="id_is_{{ type }}_{{ i }}{% if j %}_{{ j }}{% endif %}"
           class="custom-control-label"><small>チャットルーム</small></label>
</div>
<div>
    <button type="button" class="popover-btn btn btn-sm btn-outline-danger py-0 float-right mb-1"
            onclick="remove_modal(`.remove-confirm-modal`, `#{{ type }}_item_{{ i }}{% if j %}_{{ j }}{% endif %}`, `{% url 'api:remove_stream' %}`)">削除
    </button>
</div>
{% endif %}
<div>
    <button type="button" class="popover-btn btn btn-sm btn-outline-info py-0 float-right mb-1"
        onclick="notify_modal($(`.notify-setting-modal`), `{% url 'api:get_notify_modal' %}`,`{{ s.video_id }}`)">通知
    </button>
</div>
<div>
    <a class="channel-btn btn btn-sm btn-outline-info py-0 float-right mb-1" href="./channel/{{ s.channel_id }}" target="_blank">Channel Detail</a>
</div>

templates/web/channel_detail.html
{% extends "base.html" %}
{% block content %}
    This is Channel Detail page.
    {% comment %}
    TODO 配信予定と配信中をカードで表示
    TODO 再取得ボタン
    {% endcomment %}
    <p>{{ channel.title }}</p>
    <a href="{% url "api:get_stream" %}?channelId={{ channel.channel_id }}">Reload</a>
    <div class="row border border-dark rounded my-2 px-4 py-2" id="upcoming_streams">
        <h2 class="w-100">-- Stream List --</h2>
        <div class="row w-100">
            {% for stream in stream_list %}
                <div class="col-md-2 px-0 d-flex align-items-stretch yt-item yt-upcoming"
                     id="upcoming_item_{{ forloop.counter }}">
                    {% include "web/card.html" with s=stream i=forloop.counterr type="upcoming" user=user %}
                </div>
            {% endfor %}
        </div>
    </div>
    {% include "web/../notify/notify_modal.html" %}
    <script>
        (function () {
            window.addEventListener("load", function () {
                $('[data-toggle="popover"]').popover(
                    {
                        trigger: "focus",
                        html: true,
                        offset: "100",
                        sanitize: false
                    }
                );
            });
        })();
    </script>

{% endblock %}

templates/web/index.html
{% extends "base.html" %}
{% comment %}
DONE: 配信中を一番上のRowにカードで表示
DONE: 配信予定を次のRowにカードで表示
TODO: 一応、手動更新ボタンも
TODO: Periodic Taskの状態を取得し切り替えできるように(admin only)
DONE: Popoverでチャットルームに指定できるように。＋ JSで移動＋DBに登録(admin only)
DONE: Darkmode
DONE: 枠取り直しで非公開化された放送を破棄できるように(admin only)
TODO: メール送信機能
TODO: 通知機能
{% endcomment %}
{% block content %}
    {% include "web/main.html" %}
{% endblock %}

{% block auto_reflesh %}
    <div class="nav-item custom-control custom-switch d-flex align-items-center mr-4">
        <input type="checkbox" class="custom-control-input" id="switch_auto_refresh">
        <label for="switch_auto_refresh" class="custom-control-label">自動更新</label>
    </div>
    <script>
    if (typeof auto_reflesh === "undefined") {
        const auto_reflesh = setInterval(function () {
            if ($("#switch_auto_refresh").is(":checked")) {
            refresh('{% url "api:refresh" %}')
            }
        }, 60000);
    }
</script>
{% endblock %}

templates/web/main.html
<div class="row border border-dark rounded my-2 px-4 py-2" id="live_streams">
    <h2 class="w-100">-- Now Streaming --</h2>
    {% for stream in live_list %}
        <div class="col-lg-2 px-0 d-flex align-items-stretch yt-item yt-live" style="max-width: 16rem;min-width: 10rem;"
             id="live_item_{{ forloop.counter }}">
            {% include "web/card.html" with s=stream i=forloop.counter j=forloop.parentloop.counter type="live" %}
        </div>
    {% endfor %}
</div>


<div class="row border border-dark rounded my-2 px-4 py-2" id="upcoming_streams">
    <h2 class="w-100">-- Upcoming stream --</h2>
    {% for d, streams in stream_list %}
        <div class="row w-100">
            <h4 class="w-100 ml-2">{{ d }}</h4>
            {% for stream in streams %}
                <div class="col-xl-2 px-0 d-flex align-items-stretch yt-item yt-upcoming" style="max-width: 16rem"
                     id="upcoming_item_{{ forloop.parentloop.counter }}_{{ forloop.counter }}">
                    {% include "web/card.html" with s=stream i=forloop.parentloop.counter j=forloop.counter type="upcoming" user=user notice_list=notice_list %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>

<div class="row border border-dark rounded my-2 px-4 py-2" id="freechat_streams">
    <h2 class="w-100">-- Free chat --</h2>
    {% for stream in freechat_list %}
        <div class="col-xl-2 px-0 d-flex align-items-stretch yt-item yt-freechat" style="max-width: 16rem"
             id="freechat_item_{{ forloop.counter }}">
            {% include "web/card.html" with type="freechat" s=stream i=forloop.counter type="freechat" %}
        </div>
    {% endfor %}
</div>


<div class="modal fade remove-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">動画を除外</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger mr-auto remove-btn" data-dismiss="modal" onclick="">削除
                </button>
                <button type="button" class="btn btn-secondary float-right" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% include "web/../notify/notify_modal.html" %}

<script>
    (function () {
        window.addEventListener("load", function () {
            $('[data-toggle="popover"]').popover(
                {
                    trigger: "focus",
                    html: true,
                    offset: "100",
                    sanitize: false
                }
            );
        });
    })();
</script>

templates/web/top.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="head-image text-center">
            <img class="w-75" src="{% static 'images/YoutubeLiveSchedulerHeader.jpg' %}" alt="">
        </div>
        <div class="text-center mt-3 w-50 mx-auto border-top border-bottom border-dark p-2">
            <a href="{% url 'accounts:signup' %}" class="btn btn-info mx-2">新規登録</a>
            <a href="{% url 'login' %}" class="btn btn-info mx-2">ログイン</a>
        </div>
        <div class="text-center">
            <p>
                Youtube Live 管理サイト<br>
                見づらい公式の生放送一覧画面に代わり、放送予定の動画を表示します。
            </p>
        </div>
    </div>
{% endblock %}

templates/web/user_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="align-content-center">
        <div class="row w-75 mx-auto mt-4">
            <div class="col-sm-8">
                <h1>{{ user.nickname }}</h1>
                <p>{{ user.channel_id }}</p>
                {% if user.is_superuser %}
                    <p>Super User</p>
                {% endif %}
                <a class="btn btn-outline-primary" href="{% url "web:user_update" %}">Change</a>
                <script src="{% static "js/subscription.js" %}"></script>
                <button class="btn btn-outline-primary" id="reload"
                        onclick="getSubscriptions('{% url "api:register_subscription" %}'); this.disabled = true;">Reload
                </button>
            </div>
            <div class="col-sm-4">
                <img src="https://yt3.ggpht.com/a-/AOh14Gi-SFXItsu3cM_bETcrMrJWZsJQAObrFUD2AHod=s100-c-k-c0xffffffff-no-rj-mo" alt="">
            </div>
        </div>
        <div class="row w-75 mx-auto mt-4">
            <table class="table table-hover border">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">チャンネル名</th>
                    <th scope="col">URL</th>
                </tr>
                </thead>
                <tbody>
                {% for c in user.channel.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url "web:channel_detail" c.channel_id %}">{{ c.title }}</a></td>
                        <td><a href="https://www.youtube.com/channel/{{ c.channel_id }}" class="golink" target="_blank">Link</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}