VTuberSchedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("accounts.urls", namespace="accounts")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls", namespace="api")),
    path("webpush/", include("webpush.urls")),
    path("", include("web.urls", namespace="web"))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [path("signup/", views.SignUp.as_view(), name="signup")]

api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("get_stream", views.get_stream_list, name="get_stream"),
    path("notify-modal", views.get_notify_modal, name="get_notify_modal"),
    path("register_subscription", views.register_sub_channel, name="register_subscription"),
    path("set_is_freechat", views.set_is_freechat, name="set_is_freechat"),
    path("remove_stream", views.remove_stream, name="remove_stream"),
    path("refresh", views.refresh, name="refresh"),
    path("notify", views.notify, name="notify"),
    path("youtube_callback", views.youtube_callback, name="youtube_callback")
]

web/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "web"
urlpatterns = [
    path("user", views.user_detail, name="user_detail"),
    path("user/update", login_required(views.UserUpdateView.as_view()), name="user_update"),
    path("channel/<slug:channel_id>", views.channel_detail, name="channel_detail"),
    path("test", views.test, name="test"),
    path("top", views.index, name="top"),
    path("", views.index, name="index"),

]

templates/base.html
{% load static %}
{% load webpush_notifications %}
{% load webpush_head %}
{% load webpush_switch %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>Youtube Live Scheduler</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {#favicon#}
    <link rel="apple-touch-icon" sizes="57x57" href={% static 'images/favicon/apple-icon-57x57.png' %}>
    <link rel="apple-touch-icon" sizes="60x60" href={% static 'images/favicon/apple-icon-60x60.png' %}>
    <link rel="apple-touch-icon" sizes="72x72" href={% static 'images/favicon/apple-icon-72x72.png' %}>
    <link rel="apple-touch-icon" sizes="76x76" href={% static 'images/favicon/apple-icon-76x76.png' %}>
    <link rel="apple-touch-icon" sizes="114x114" href={% static 'images/favicon/apple-icon-114x114.png' %}>
    <link rel="apple-touch-icon" sizes="120x120" href={% static 'images/favicon/apple-icon-120x120.png' %}>
    <link rel="apple-touch-icon" sizes="144x144" href={% static 'images/favicon/apple-icon-144x144.png' %}>
    <link rel="apple-touch-icon" sizes="152x152" href={% static 'images/favicon/apple-icon-152x152.png' %}>
    <link rel="apple-touch-icon" sizes="180x180" href={% static 'images/favicon/apple-icon-180x180.png' %}>
    <link rel="icon" type="image/png" sizes="192x192" href={% static 'images/favicon/android-icon-192x192.png' %}>
    <link rel="icon" type="image/png" sizes="32x32" href={% static 'images/favicon/favicon-32x32.png' %}>
    <link rel="icon" type="image/png" sizes="96x96" href={% static 'images/favicon/favicon-96x96.png' %}>
    <link rel="icon" type="image/png" sizes="16x16" href={% static 'images/favicon/favicon-16x16.png' %}>
    <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{% static "style.css" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"
            integrity="sha384-3Nqiqht3ZZEO8FKj7GR1upiI385J92VwWNLj+FqHxtLYxd9l+WYpeqSOrLh0T12c"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.6/lib/darkmode-js.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/push.js/1.0.12/push.min.js"
            integrity="sha512-DjIQO7OxE8rKQrBLpVCk60Zu0mcFfNx2nVduB96yk5HS/poYZAkYu5fxpwXj3iet91Ezqq2TNN6cJh9Y5NtfWg=="
            crossorigin="anonymous"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PLDM8X50N1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'G-PLDM8X50N1');
    </script>
    {% webpush_head_script %}
    {% webpush_head_worker %}
    {% webpush_head_vapid %}
    {% block head_script %}{% endblock %}
</head>
<body class="d-flex flex-column">
<div class="container-fluid" id="container">
    <header class="w-75 mx-auto">
        <nav class="navbar navbar-expand-lg navbar-light bg-light rounded-bottom py-1">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="/" class="nav-link"><img
                        src="{% static 'images/YoutubeLiveSchedulerLogo.svg' %}" alt="" style="height: 2rem;"></a></li>
                <li class="nav-item my-auto"><a href="/" class="nav-link">Home</a></li>
            </ul>
            <ul class="navbar-nav">
                {% block auto_reflesh %}
                {% endblock %}
                <div class="nav-item custom-control custom-switch d-flex align-items-center mr-4">
                    <input type="checkbox" class="custom-control-input" id="switch_darkmode"
                           onclick="darkmode.toggle()">
                    <label for="switch_darkmode" class="custom-control-label">Darkmode</label>
                </div>
                {% if user.is_authenticated %}
                    {% webpush_switch %}
                    <li class="nav-item"><a href="{% url 'web:user_detail' %}"
                                            class="user nav-link">{{ user.username }}</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="logout nav-link">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="signup nav-link">Sign up</a></li>
                    <li class="nav-item"><a href="{% url 'login' %}" class="login nav-link">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="content mx-auto my-4">
        {% block content %}{% endblock %}
    </div>
</div>
<footer class="footer w-100 text-center bg-light">
    <div class="container h-100 ">
        <small class="text-muted align-middle">Created by KK - 2020</small>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static "js/utils.js" %}"></script>
<script src="{% static "js/modals.js" %}"></script>

<script>
    const darkmode = new Darkmode();
    if (darkmode.isActivated()) {
        $("#switch_darkmode").prop("checked", true);
    } else {
        $("#switch_darkmode").prop("checked", false);
    }
</script>
</body>
</html>